[workspace]
members = [
    "protocol",
    "fabric_client",
    "server_test",
    "client_test",
    "mp4",
    "wasm_util",
    "orchestrator/native/livecorenode",
]

[profile.release]
debug = true
